### ISSUE TITLE
Custom CSS in vignette

### ISSUE THREAD

**Issue by TobiasFellinger** [etiennebacher/tidypolars#150] opened 2024-10-30 08:54 UTC
In the getting started vignette content of code tags within divs of the custom_note class is white font on very bright background when displayed in Rstudio (see screenshot). A quick check with inspect element suggests, that the background color is defined in the file https://r-universe.dev/static/article-styles.css . I did not find out where this file is included.

To reproduce: install the latest release and open the vignette in Rstudio. (I have Rstudio set to the bright colorscheme, in case this makes a difference.)

![grafik](https://github.com/user-attachments/assets/ad342f6b-b084-41b7-90d9-717190128e1b)

**Comment by etiennebacher** [comment] 2024-10-30 08:58
Hi, thank you for the report, I can reproduce. I'll try to fix this ASAP, in the meantime you can see the vignette on the website: https://www.tidypolars.etiennebacher.com/articles/tidypolars

**Comment by etiennebacher** [comment] 2024-10-30 09:22
This should be fixed. Reinstall the development version with

```r
remotes::install_github("etiennebacher/tidypolars", build_vignettes = TRUE)
```

Feel free to reopen if the issue is still there.

**Closed by etiennebacher** 2024-10-30 09:22 UTC
Labels: bug

**Comment by TobiasFellinger** [comment] 2024-10-30 09:26
That was quick, works perfectly thank you!
